"""analyzer_bundle.py - GENERATED by build.py. Do not edit.

Edit files under analyzer/ and run python build.py.
"""

import numpy as np
from pathlib import Path
from scipy.io import wavfile
from scipy.signal import find_peaks
from scipy.signal import find_peaks, get_window
from scipy.fft import rfft, rfftfreq
from scipy.signal import get_window
import hashlib
import json

############################################################
# from analyzer/config.py
############################################################
"""Cross-cutting constants. Things that don't belong to any one stage."""

SCHEMA_VERSION = 1
KIND = 'kick'

# f0 consensus: agreement above this flags an f-ambiguous sample.
F_AGREE_FLAG_HZ = 5.0

# Multi-method f0 search band defaults.
F0_LO_HZ = 25.0
F0_HI_HZ = 250.0

# Class discriminator: raw_peak_ms at or below this -> fishtail.
# Above -> swell. See PROJECT_STATE §3 (S5 finding).
FISHTAIL_PEAK_MAX_MS = 8.0

# Content-ID: how much of the head to hash, and hash length.
ID_SECONDS = 5.0
ID_HASH_LEN = 12

############################################################
# from analyzer/io.py
############################################################
"""Audio loading. WAV and CSV in, (samples, sr, meta) out.

Depends on: numpy, scipy.io.wavfile
Used by:    analyzer.pipeline
"""



def load_audio(path):
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(str(path))
    ext = p.suffix.lower()
    if ext == '.wav':
        return _load_wav(p)
    if ext == '.csv':
        return _load_csv(p)
    raise ValueError("Unsupported: " + ext)


def _load_wav(p):
    sr, data = wavfile.read(str(p))
    if data.dtype == np.int16:
        x = data.astype(np.float32) / 32768.0
    elif data.dtype == np.int32:
        x = data.astype(np.float32) / 2147483648.0
    elif data.dtype == np.uint8:
        x = (data.astype(np.float32) - 128.0) / 128.0
    else:
        x = data.astype(np.float32)
    if x.ndim == 2:
        x = x.mean(axis=1)
    return x, float(sr), {'format': 'wav', 'sr_nominal': int(sr),
                          'path': str(p)}


def _load_csv(p):
    import pandas as pd
    df = pd.read_csv(str(p), sep=None, engine='python')
    df = df.dropna(axis=1, how='all')
    cols = df.columns.tolist()
    tname = cols[0]
    for c in cols:
        if 'time' in str(c).lower():
            tname = c
            break
    t = df[tname].values.astype(float)
    sig = [c for c in cols if c != tname]
    x = df[sig].mean(axis=1).values.astype(np.float32)
    sr = 1.0 / float(np.median(np.diff(t)))
    return x, sr, {'format': 'csv', 'sr_effective': sr, 'path': str(p)}

############################################################
# from analyzer/onsets.py
############################################################
"""Onset detection and loop grouping.

S5 BUG C: onset detector locks onto the swell peak on swell-class kicks.
Do not fix without user sign-off; see PROJECT_STATE §5.3 (Bug C).
Touches: detect_onsets.

Depends on: numpy, scipy.signal.find_peaks
Used by:    analyzer.pipeline
"""



def detect_onsets(x, sr, min_distance_ms=200):
    """BUG C: onset detector locks onto the swell peak on swell-class
    kicks. Mid's dual-class reading is the confirmed case.
    Do not fix without user sign-off."""
    win = max(4, int(8 * sr / 1000))
    hop = max(1, int(2 * sr / 1000))
    n = max(1, 1 + (len(x) - win) // hop)
    if n < 2:
        return np.array([0], dtype=int)
    e = np.array([float(np.sum(x[i * hop:i * hop + win] ** 2))
                  for i in range(n)])
    if len(e) > 3:
        e = np.convolve(e, np.ones(3) / 3, mode='same')
    d = np.maximum(np.diff(e, prepend=0.0), 0.0)
    if d.max() <= 0:
        return np.array([0], dtype=int)
    md = max(1, int(min_distance_ms * sr / 1000 / hop))
    pk, _ = find_peaks(d, distance=md, prominence=d.max() * 0.15)
    onsets = pk * hop if len(pk) else np.array([0], dtype=int)
    near_start = int(20 * sr / 1000)
    if len(onsets) > 0 and onsets[0] < near_start:
        onsets = np.concatenate([[0], onsets[1:]])
    elif len(onsets) > 0 and onsets[0] > int(10 * sr / 1000):
        head = x[:int(10 * sr / 1000)]
        if len(head) > 0 and np.max(np.abs(head)) > 0.3 * np.max(np.abs(x)):
            min_sep = int(min_distance_ms * sr / 1000)
            keep = onsets > min_sep
            onsets = np.concatenate([[0], onsets[keep]])
    return onsets


def group_onsets(x, sr, onsets, window_ms=400, threshold=0.85,
                 max_lag_ms=8):
    """Group onsets into classes by lag-tolerant correlation."""
    n = len(onsets)
    if n == 0:
        return np.array([]), {}
    if n == 1:
        return np.array([0]), {0: [0]}
    wl = int(min(window_ms, len(x) / sr * 1000) * sr / 1000)
    segs, valids = [], []
    for o in onsets:
        end = min(o + wl, len(x))
        s = x[o:end].astype(np.float32).copy()
        real_len = len(s)
        idx = _attack_align_idx(s, sr, head_ms=30)
        if idx > 0:
            s = s[idx:]
            real_len -= idx
        segs.append(s)
        valids.append(real_len)
    for i, s in enumerate(segs):
        v = valids[i]
        if v > 0:
            segs[i] = s - float(np.mean(s[:v]))
    max_lag = int(max_lag_ms * sr / 1000)
    labels = np.full(n, -1, dtype=int)
    cid = 0
    for i in range(n):
        if labels[i] >= 0:
            continue
        labels[i] = cid
        for j in range(i + 1, n):
            if labels[j] >= 0:
                continue
            c = _lag_corr(segs[i], segs[j], max_lag, valids[i], valids[j])
            if c > threshold:
                labels[j] = cid
        cid += 1
    cls = {}
    for i, l in enumerate(labels):
        cls.setdefault(int(l), []).append(i)
    return labels, cls


def _attack_align_idx(seg, sr, head_ms=30):
    n = min(int(head_ms * sr / 1000), len(seg))
    if n < 4:
        return 0
    return int(np.argmax(np.abs(seg[:n])))


def _lag_corr(a, b, max_lag, va, vb):
    best = -2.0
    for lag in range(-max_lag, max_lag + 1):
        if lag < 0:
            a_off, b_off = -lag, 0
        elif lag > 0:
            a_off, b_off = 0, lag
        else:
            a_off, b_off = 0, 0
        m = min(va - a_off, vb - b_off)
        if m < 64:
            continue
        aa = a[a_off:a_off + m]
        bb = b[b_off:b_off + m]
        na = np.sqrt(np.sum(aa * aa)) + 1e-10
        nb = np.sqrt(np.sum(bb * bb)) + 1e-10
        c = float(np.sum(aa * bb) / (na * nb))
        if c > best:
            best = c
    return best

############################################################
# from analyzer/envelope.py
############################################################
"""Envelope extraction, landmarks, and settled-body detection.

S5 BUG B: find_landmarks valley prominence threshold is relative to the
attack level, not the local envelope height. Saturated/rising kicks do
not dip 5% below attack. Do not fix without user sign-off;
see PROJECT_STATE §5.3 (Bug B). Touches: find_landmarks.

S5 BUG A: _find_settled_body returns None on late-peak kicks. Do not fix
without user sign-off; see PROJECT_STATE §5.3 (Bug A).
Touches: _find_settled_body. Called from analyzer.pitch.

Depends on: numpy, scipy.signal.find_peaks
Used by:    analyzer.pipeline, analyzer.pitch
"""



def cycle_peak_envelope(x, sr):
    """Return (t_ms, |peak|) per zero-crossing-bounded half-cycle."""
    if len(x) < 4:
        return np.array([]), np.array([])
    s = np.sign(x)
    s[s == 0] = 1
    zc = np.where(np.diff(s) != 0)[0] + 1
    if len(zc) < 2:
        return np.array([]), np.array([])
    t_o, v_o = [], []
    for k in range(len(zc) - 1):
        a, b = zc[k], zc[k + 1]
        if b - a < 2:
            continue
        sub = x[a:b]
        idx = int(np.argmax(np.abs(sub)))
        t_o.append((a + idx) / sr * 1000)
        v_o.append(abs(float(sub[idx])))
    return np.array(t_o), np.array(v_o)


def sliding_window_envelope(x, sr, win_ms=2.0, hop_ms=0.25):
    w = max(1, int(win_ms * sr / 1000))
    hop = max(1, int(hop_ms * sr / 1000))
    a = np.abs(x)
    n = max(1, 1 + (len(a) - w) // hop)
    env = np.array([float(a[i * hop:i * hop + w].max())
                    for i in range(n)])
    return np.arange(n) * hop / sr * 1000, env


def find_landmarks(t, v, seg_peak):
    """BUG B: valley prominence is relative to attack, not local height.
    Do not fix without user sign-off. Returns the envelope landmark dict."""
    if len(t) < 4 or seg_peak <= 0:
        return {}
    within = t <= 5.0
    if within.any():
        idx_w = np.where(within)[0]
        i_a = int(idx_w[0] + np.argmax(v[idx_w]))
    else:
        i_a = int(np.argmax(v))
    atk_t = float(t[i_a])
    atk_lvl = float(v[i_a])
    if atk_lvl <= 0:
        return {}
    o = {'attack_t_ms': atk_t, 'attack_level': atk_lvl,
         'seg_peak': float(seg_peak)}
    after = t > atk_t + 1.0
    if not after.any():
        return o
    t_a = t[after]
    v_a = v[after]
    prom = 0.05 * atk_lvl
    valleys, _ = find_peaks(-v_a, prominence=prom)
    peaks, _ = find_peaks(v_a, prominence=prom)
    if len(valleys) > 0:
        iv = valleys[0]
        o['valley_t_ms'] = float(t_a[iv])
        o['valley_level_pct'] = float(100 * v_a[iv] / atk_lvl)
        rp = peaks[peaks > iv]
        if len(rp) > 0:
            ir = rp[0]
            o['reswell_t_ms'] = float(t_a[ir])
            o['reswell_level_pct'] = float(100 * v_a[ir] / atk_lvl)
    o['n_peaks'] = int(len(peaks))
    if len(peaks) >= 1:
        o['peak2_t_ms'] = float(t_a[peaks[0]])
        o['peak2_level_pct'] = float(100 * v_a[peaks[0]] / atk_lvl)
    if len(peaks) >= 2:
        o['peak3_t_ms'] = float(t_a[peaks[1]])
        o['peak3_level_pct'] = float(100 * v_a[peaks[1]] / atk_lvl)
    for q, k in [(100.0, 'body_100ms_pct'), (200.0, 'lvl_200ms_pct')]:
        o[k] = float(100 * np.interp(q, t, v) / atk_lvl)
    ab = np.where(v / atk_lvl > 0.01)[0]
    if len(ab):
        o['duration_ms'] = float(t[ab[-1]])
    return o


def _find_settled_body(t_env, v_env, seg_ms,
                       settle_offset_ms=20.0,
                       max_after_peak_ms=90.0,
                       min_body_ms=40.0,
                       floor_frac=0.3):
    """BUG A: returns None on late-peak kicks (Roundhouse, UnderGroover,
    FL Synth, Thin). Do not fix without user sign-off.
    Called from analyzer.pitch.settled_fundamental and measure_f0_multi
    via _resolve_body_and_f0."""
    if len(t_env) == 0 or float(np.max(v_env)) <= 0:
        return None
    vmax = float(np.max(v_env))
    after = t_env > 10.0
    if after.sum() < 3:
        return None
    idxs = np.where(after)[0]
    i_pk = int(idxs[np.argmax(v_env[idxs])])
    t_peak = float(t_env[i_pk])
    floor = floor_frac * vmax
    t_end_limit = t_peak + max_after_peak_ms
    i = i_pk
    while (i < len(v_env) - 1
           and t_env[i + 1] < t_end_limit
           and v_env[i + 1] >= floor):
        i += 1
    t_end = float(t_env[i])
    t_start_pref = t_peak + settle_offset_ms
    if t_end - t_start_pref >= min_body_ms:
        return (t_start_pref, t_end)
    if t_end - t_peak >= min_body_ms:
        return (t_peak, t_end)
    return None

############################################################
# from analyzer/pitch_methods.py
############################################################
"""f0 estimators. Registry pattern.

Adding a method:
    @f0_method('name')
    def _f0_name(body, sr, lo_hz, hi_hz):
        ...
        return float_or_None

That's the whole extension mechanism. `measure_f0_multi` in pitch.py
loops over the registry. No other file needs to change.

Depends on: numpy, scipy.signal.find_peaks, scipy.signal.get_window,
            scipy.fft.rfft/rfftfreq
Optional:   librosa (for pYIN; unavailable in Pyodide)
Used by:    analyzer.pitch
"""


try:
    import librosa
    HAS_LIBROSA = True
except ImportError:
    HAS_LIBROSA = False


F0_METHODS = {}


def f0_method(name):
    """Register an f0 method. Signature: fn(body, sr, lo, hi) -> float|None."""
    def deco(fn):
        F0_METHODS[name] = fn
        return fn
    return deco


def pitch_cycle_length(x, sr, min_c=3):
    """Cycle-by-cycle pitch from zero-crossing intervals."""
    s = np.sign(x)
    s[s == 0] = 1
    zc = np.where(np.diff(s) != 0)[0] + 1
    if len(zc) < 2:
        return np.array([]), np.array([])
    t_o, f_o = [], []
    for k in range(len(zc) - 1):
        n = zc[k + 1] - zc[k]
        if n < min_c:
            continue
        t_o.append((zc[k] + zc[k + 1]) / 2 / sr * 1000)
        f_o.append(0.5 * sr / n)
    return np.array(t_o), np.array(f_o)


def pitch_pyin(x, sr, fmin=30.0, fmax=None):
    """pYIN via librosa. Returns (t_ms, f0) or (None, None)."""
    if not HAS_LIBROSA or len(x) < 512:
        return None, None
    if fmax is None:
        fmax = min(2000.0, sr / 2 * 0.95)
    need = int(2.2 * sr / fmin)
    fl = max(2048, need)
    fl = min(fl, len(x) if len(x) % 2 == 0 else len(x) - 1)
    if fl % 2:
        fl -= 1
    if fl < 512:
        return None, None
    try:
        f0, _, _ = librosa.pyin(x, fmin=fmin, fmax=fmax, sr=sr,
                                frame_length=fl)
        hop = 512
        t = np.arange(len(f0)) * hop / sr * 1000
        return t, np.where(np.isnan(f0), 0, f0)
    except Exception:
        return None, None


# -------- registered estimators --------

@f0_method('spectral')
def _f0_spectral(body, sr, lo_hz, hi_hz):
    """First prominent spectral peak in band (bin resolution)."""
    N = 8192
    b = body[:N] if len(body) >= N else np.pad(body, (0, N - len(body)))
    spec = np.abs(rfft(b * get_window('hann', N)))
    fr = rfftfreq(N, 1 / sr)
    band = (fr >= lo_hz) & (fr <= hi_hz)
    if not band.any() or spec[band].max() <= 0:
        return None
    pk, _ = find_peaks(spec[band], height=spec[band].max() * 0.1)
    if not len(pk):
        return None
    return float(fr[band][pk[0]])


@f0_method('zc')
def _f0_zc(body, sr, lo_hz, hi_hz):
    """Median zero-crossing-interval frequency. Fragile on chirps."""
    z = body - body.mean()
    s = np.sign(z)
    s[s == 0] = 1
    zc = np.where(np.diff(s) != 0)[0]
    if len(zc) <= 4:
        return None
    fz = 0.5 / (np.diff(zc) / sr)
    fz = fz[(fz > lo_hz) & (fz < 400.0)]
    if len(fz) < 3:
        return None
    return float(np.median(fz))


@f0_method('autocorr')
def _f0_autocorr(body, sr, lo_hz, hi_hz):
    """First AC peak after first zero-crossing (S4 fix - no shoulder bias)."""
    a = body - body.mean()
    if len(a) < 64:
        return None
    ac = np.correlate(a, a, mode='full')[len(a) // 2:]
    if ac[0] <= 0:
        return None
    ac = ac / ac[0]
    sgn = np.sign(ac)
    sgn[sgn == 0] = 1
    dz = np.diff(sgn)
    zc_ac = np.where(dz < 0)[0] + 1
    if len(zc_ac) == 0:
        return None
    first_zc = int(zc_ac[0])
    pk_ac, _ = find_peaks(ac, height=0.0)
    pk_ac = pk_ac[pk_ac > first_zc]
    if len(pk_ac) == 0:
        return None
    lag = int(pk_ac[0])
    if lag <= 0:
        return None
    return float(sr / lag)


@f0_method('pyin')
def _f0_pyin(body, sr, lo_hz, hi_hz):
    """pYIN median. Skipped when librosa is unavailable (Pyodide)."""
    if not HAS_LIBROSA:
        return None
    fmin_py = max(lo_hz, 2.2 * sr / len(body))
    if fmin_py >= hi_hz:
        return None
    _, py = pitch_pyin(body, sr, fmin=fmin_py, fmax=hi_hz)
    if py is None:
        return None
    v = py[py > 0]
    if len(v) < 3:
        return None
    return float(np.median(v))

############################################################
# from analyzer/pitch.py
############################################################
"""f0 consensus + settled fundamental.

Depends on: numpy, analyzer.pitch_methods, analyzer.envelope
Used by:    analyzer.pipeline
"""




def measure_f0_multi(body, sr, lo_hz=F0_LO_HZ, hi_hz=F0_HI_HZ):
    """Run every registered method, MAD-exclude outliers, return median.
    Returns dict: {f0, methods, agreement_hz, window_ms, flag,
                   n_excluded, excluded}."""
    out = {'f0': None, 'methods': {}, 'agreement_hz': None,
           'window_ms': None, 'flag': None,
           'n_excluded': 0, 'excluded': []}
    if body is None or len(body) < 2048:
        out['flag'] = 'too_short'
        return out

    for name, fn in F0_METHODS.items():
        try:
            v = fn(body, sr, lo_hz, hi_hz)
        except Exception:
            v = None
        if v is not None:
            out['methods'][name] = float(v)

    vals = {k: v for k, v in out['methods'].items() if v is not None}
    if len(vals) < 2:
        if len(vals) == 1:
            out['f0'] = list(vals.values())[0]
            out['flag'] = 'single_method'
        else:
            out['flag'] = 'no_method_succeeded'
        return out

    arr = np.array(list(vals.values()))
    med = float(np.median(arr))
    devs = np.abs(arr - med)
    mad = float(np.median(devs))
    if mad < 0.5:
        mad = 1.0
    keep_mask = devs <= 3.0 * mad
    if keep_mask.sum() < 3 and len(arr) >= 3:
        order = np.argsort(devs)
        keep_mask = np.zeros(len(arr), dtype=bool)
        keep_mask[order[:3]] = True

    names = list(vals.keys())
    inliers = [names[i] for i in range(len(names)) if keep_mask[i]]
    excluded = [names[i] for i in range(len(names)) if not keep_mask[i]]
    out['excluded'] = excluded
    out['n_excluded'] = len(excluded)

    inlier_vals = [vals[k] for k in inliers]
    out['f0'] = float(np.median(inlier_vals))
    if len(inlier_vals) >= 2:
        out['agreement_hz'] = float(max(inlier_vals) - min(inlier_vals))
    if len(inlier_vals) < 3:
        out['flag'] = 'weak_consensus'
    return out


def settled_fundamental(t, f, env_t=None, env_v=None, seg_ms=None):
    """Median f0 over the settled body window (see _find_settled_body).
    Returns None if no settled body is found."""
    if len(t) < 4:
        return None
    if env_t is None or env_v is None or len(env_v) == 0:
        t_lo, t_hi = float(t[0]), float(t[-1])
    else:
        if seg_ms is None:
            seg_ms = float(env_t[-1]) if len(env_t) else float(t[-1])
        win = _find_settled_body(env_t, env_v, seg_ms)
        if win is None:
            return None
        t_lo, t_hi = win
    t_lo = max(t_lo, float(t[0]))
    t_hi = min(t_hi, float(t[-1]))
    if t_hi - t_lo < 20.0:
        return None
    grid = np.linspace(t_lo, t_hi, 50)
    f_grid = np.interp(grid, t, f)
    f_grid = f_grid[f_grid > 20.0]
    if len(f_grid) < 10:
        return None
    return float(np.median(f_grid))

############################################################
# from analyzer/spectral.py
############################################################
"""STFT, spectral centroid, click detection, harmonic ratio.

Depends on: numpy, scipy.signal.get_window, scipy.fft.rfft/rfftfreq
Used by:    analyzer.pipeline
"""



def compute_stft(x, sr, n_fft=1024, hop=None, pad_start=True):
    if hop is None:
        hop = n_fft // 4
    pad = n_fft // 2 if pad_start else 0
    if len(x) < n_fft:
        x = np.pad(x, (0, n_fft - len(x)))
    if pad > 0:
        x = np.pad(x, (pad, 0))
    win = get_window('hann', n_fft)
    nf = max(1, 1 + (len(x) - n_fft) // hop)
    S = np.zeros((n_fft // 2 + 1, nf), dtype=np.complex128)
    for i in range(nf):
        S[:, i] = rfft(x[i * hop:i * hop + n_fft] * win)
    times = (np.arange(nf) * hop + n_fft / 2 - pad) / sr * 1000
    return np.abs(S), rfftfreq(n_fft, 1 / sr), times


def spectral_centroid(S, freqs, times, envelope_t=None, envelope_v=None,
                      floor_pct=0.02):
    num = (freqs[:, None] * S).sum(axis=0)
    den = S.sum(axis=0)
    safe = np.where(den > 0, den, 1e-10)
    cen = num / safe
    if (envelope_t is not None and envelope_v is not None
            and len(envelope_v) > 0):
        peak = float(np.max(envelope_v))
        if peak > 0:
            floor = floor_pct * peak
            env_at_frames = np.interp(times, envelope_t, envelope_v)
            cen = np.where(env_at_frames > floor, cen, np.nan)
    return cen


def _body_frames(S, quantile=0.5):
    total = S.sum(axis=0)
    if not np.any(total > 0):
        return np.zeros(S.shape[1], dtype=bool)
    thr = np.quantile(total, quantile)
    return total >= thr


def detect_click(S, freqs, times, f0):
    """True + ratio(dB) if the first 3 frames have >2*f0 energy >6 dB
    above the body frames' >2*f0 energy. Else False, None."""
    if not f0 or f0 <= 0:
        return False, None
    hf = freqs > 2 * f0
    if not hf.any() or S.shape[1] < 5:
        return False, None
    click_frames = np.zeros(S.shape[1], dtype=bool)
    click_frames[:3] = True
    body_frames = _body_frames(S, 0.5) & ~click_frames
    if not body_frames.any() or not click_frames.any():
        return False, None
    hf_click = float(S[np.ix_(hf, click_frames)].mean()) + 1e-10
    hf_body = float(S[np.ix_(hf, body_frames)].mean()) + 1e-10
    r = float(20 * np.log10(hf_click / hf_body))
    return r > 6.0, r


def harmonic_ratio_db(S, freqs, times, f0, seg=None, sr=44100):
    """2*f0 vs f0 energy, from a dedicated 8192-pt FFT of the 150-300 ms
    body slice. Not from the STFT."""
    if not f0 or f0 <= 0 or seg is None or len(seg) < 4096:
        return None
    sr_f = float(sr)
    t_lo, t_hi = 150.0, min(300.0, len(seg) / sr_f * 1000.0)
    if t_hi - t_lo < 50.0:
        t_lo, t_hi = 100.0, min(250.0, len(seg) / sr_f * 1000.0)
        if t_hi - t_lo < 50.0:
            return None
    s0 = max(0, int(t_lo * 1e-3 * sr_f))
    s1 = min(len(seg), int(t_hi * 1e-3 * sr_f))
    if s1 - s0 < 2048:
        return None
    body = seg[s0:s1]
    n_fft = 8192
    if len(body) < n_fft:
        body = np.pad(body, (0, n_fft - len(body)))
    else:
        body = body[:n_fft]
    win = get_window('hann', n_fft)
    spec = np.abs(rfft(body * win))
    fr = rfftfreq(n_fft, 1 / sr_f)
    bw = max(2.0, (sr_f / n_fft) * 1.5)

    def band(fc):
        if fc <= 0:
            return 1e-10
        m = (fr >= fc - bw) & (fr <= fc + bw)
        if not m.any():
            return 1e-10
        return float(spec[m].mean()) + 1e-10

    return float(20 * np.log10(band(2 * f0) / band(f0)))

############################################################
# from analyzer/pipeline.py
############################################################
"""Top-level pipeline. Reads top to bottom as the analyzer's story.

    analyze_array / analyze_file          entry points
      -> normalize, detect_onsets, group_onsets
      -> for each class: _extract_segment -> analyze_kick
          -> envelope, landmarks, pitch, spectral
      -> assemble

The fingerprint shape (flat, per PROJECT_STATE S7) is built in
analyze_kick.

Depends on: everything in this package
Used by:    index.html (via analyzer_bundle.py), analyzer.batch,
            cluster.load (indirectly, via data/fingerprints/)
"""





# =====================================================================
# public entry points
# =====================================================================
def analyze_file(path, window_ms=500, headroom_ms=40,
                 save_json=False, verbose=False):
    x, sr, meta = load_audio(path)
    res = _run(x, sr, meta, source=str(path),
               window_ms=window_ms, headroom_ms=headroom_ms)
    if verbose:
        print_report(res)
    if save_json:
        out = Path(path).with_suffix('.fingerprint.json')
        with open(str(out), 'w') as f:
            json.dump(to_json(res), f, indent=2)
        if verbose:
            print("Saved: " + str(out))
    return res


def analyze_array(x, sr, source='<array>', window_ms=500, headroom_ms=40,
                  verbose=False):
    meta = {'format': 'array', 'sr_nominal': int(sr), 'path': source}
    res = _run(np.asarray(x, dtype=np.float32), float(sr), meta,
               source=source, window_ms=window_ms,
               headroom_ms=headroom_ms)
    if verbose:
        print_report(res)
    return res


# =====================================================================
# the pipeline
# =====================================================================
def _run(x, sr, meta, source, window_ms, headroom_ms):
    meta = _fill_meta(meta, x, sr)
    xn = _normalize(x)
    onsets = detect_onsets(xn, sr)
    labels, classes = group_onsets(xn, sr, onsets, window_ms=window_ms)

    kicks = []
    for cid in sorted(classes.keys()):
        row = _analyze_class(xn, sr, onsets, classes[cid], cid,
                             window_ms, headroom_ms)
        if row is not None:
            kicks.append(row)

    return {
        'schema_version': SCHEMA_VERSION,
        'kind': KIND,
        'id': _content_id(x, sr),
        'source': str(source),
        'meta': meta,
        'loop': _loop_summary(onsets, labels, classes),
        'kicks': kicks,
    }


def _analyze_class(xn, sr, onsets, idxs, class_id, window_ms, headroom_ms):
    seg, onset = _extract_segment(xn, sr, onsets, idxs,
                                  window_ms, headroom_ms)
    if seg is None:
        return None
    return analyze_kick(seg, sr, class_id=class_id,
                        n_instances=len(idxs),
                        onset_samples=[int(onsets[i]) for i in idxs],
                        first_onset_ms=onset / sr * 1000)


def analyze_kick(seg, sr, class_id, n_instances,
                 onset_samples, first_onset_ms):
    seg_peak = float(np.max(np.abs(seg))) if len(seg) else 1.0
    raw_peak_idx = int(np.argmax(np.abs(seg))) if len(seg) else 0
    raw_peak_ms = raw_peak_idx / sr * 1000

    t_env, v_env = cycle_peak_envelope(seg, sr)
    t_sw, v_sw = sliding_window_envelope(seg, sr)
    landmarks = find_landmarks(t_env, v_env, seg_peak)
    f0, f0_zc, f0_methods, f0_agr, f0_win, f0_flag, f0_nex, f0_excl = \
        _resolve_f0(seg, sr, t_env, v_env)
    t_p, f_p = pitch_cycle_length(seg, sr)
    t_py, f_py = pitch_pyin(seg, sr)
    S, freqs, times = compute_stft(seg, sr)
    cen = spectral_centroid(S, freqs, times, t_sw, v_sw, floor_pct=0.02)
    click, click_db = detect_click(S, freqs, times, f0)
    harm_db = harmonic_ratio_db(S, freqs, times, f0, seg=seg, sr=int(sr))

    pitch_detail = {
        'f_settled_hz': f0,
        'f_settled_zc': f0_zc,
        'f_settled_methods': f0_methods,
        'f_settled_agreement_hz': f0_agr,
        'f_settled_window_ms': f0_win,
        'f_settled_flag': f0_flag,
        'f_settled_n_excluded': f0_nex,
        'f_settled_excluded': f0_excl,
        'has_pyin': t_py is not None,
    }
    content_detail = {
        'click_present': click,
        'click_ratio_db': click_db,
        'harmonic_ratio_2f0_db': harm_db,
    }

    row = {
        'class_id': int(class_id),
        'n_instances': int(n_instances),
        'onset_samples': list(onset_samples),
        'first_onset_ms': float(first_onset_ms),
        'seg_peak': float(seg_peak),
        'raw_peak_ms': float(raw_peak_ms),
        'class': _classify(raw_peak_ms),

        'f_settled_hz': f0,
        'f_settled_agreement_hz': f0_agr,
        'duration_ms': _g(landmarks, 'duration_ms'),
        'attack_t_ms': _g(landmarks, 'attack_t_ms'),
        'valley_t_ms': _g(landmarks, 'valley_t_ms'),
        'valley_level_pct': _g(landmarks, 'valley_level_pct'),
        'reswell_t_ms': _g(landmarks, 'reswell_t_ms'),
        'reswell_level_pct': _g(landmarks, 'reswell_level_pct'),
        'body_100ms_pct': _g(landmarks, 'body_100ms_pct'),
        'lvl_200ms_pct': _g(landmarks, 'lvl_200ms_pct'),
        'click_present': click,
        'click_ratio_db': click_db,
        'harmonic_ratio_2f0_db': harm_db,

        'detail': {
            'envelope': landmarks,
            'pitch': pitch_detail,
            'content': content_detail,
        },

        '_arrays': {
            't_env': t_env, 'v_env': v_env,
            't_sw': t_sw, 'v_sw': v_sw,
            't_pitch': t_p, 'f_pitch': f_p,
            't_pyin': t_py, 'f_pyin': f_py,
            'S': S, 'freqs': freqs, 'times': times,
            'centroid': cen, 'seg': seg,
        },
    }
    row['detail']['pitch']['f_settled_hz'] = f0
    return row


# =====================================================================
# helpers
# =====================================================================
def _fill_meta(meta, x, sr):
    meta = dict(meta)
    meta['n_samples'] = int(len(x))
    meta['duration_ms'] = float(len(x) / sr * 1000)
    meta['nyquist_hz'] = float(sr / 2)
    meta['peak'] = float(np.abs(x).max())
    meta['dc_offset'] = float(x.mean())
    return meta


def _normalize(x):
    pk = np.abs(x).max()
    return x / pk if pk > 0 else x.copy()


def _extract_segment(xn, sr, onsets, idxs, window_ms, headroom_ms):
    onset = int(onsets[idxs[0]])
    after = onsets[onsets > onset]
    next_onset = int(after.min()) if len(after) else len(xn)
    headroom = int(headroom_ms * sr / 1000)
    end = min(onset + int(window_ms * sr / 1000),
              next_onset - headroom,
              len(xn))
    if end <= onset:
        return None, onset
    return xn[onset:end], onset


def _loop_summary(onsets, labels, classes):
    return {
        'n_onsets': int(len(onsets)),
        'n_classes': int(len(classes)),
        'class_sizes': [len(v) for v in classes.values()],
        'class_assignments': labels.tolist(),
        'onset_samples': onsets.tolist(),
    }


def _resolve_f0(seg, sr, t_env, v_env):
    seg_ms = len(seg) / sr * 1000.0
    win = _find_settled_body(t_env, v_env, seg_ms) if len(v_env) else None
    if win is None:
        return None, None, {}, None, None, 'no_settled_body', 0, []
    b0 = max(0, int(win[0] * 1e-3 * sr))
    b1 = min(len(seg), int(win[1] * 1e-3 * sr))
    if b1 - b0 < 2048:
        return None, None, {}, None, None, 'body_too_short', 0, []
    body = seg[b0:b1]
    mm = measure_f0_multi(body, sr)
    t_p, f_p = pitch_cycle_length(seg, sr)
    zc_f0 = settled_fundamental(t_p, f_p, t_env, v_env)
    return (mm.get('f0'), zc_f0, mm.get('methods', {}),
            mm.get('agreement_hz'), win[1] - win[0], mm.get('flag'),
            mm.get('n_excluded', 0), mm.get('excluded', []))


def _classify(raw_peak_ms):
    if raw_peak_ms is None:
        return None
    return ('fishtail' if raw_peak_ms <= FISHTAIL_PEAK_MAX_MS
            else 'swell')


def _content_id(x, sr):
    n = min(len(x), int(ID_SECONDS * sr))
    q = np.clip(x[:n] * 32767, -32768, 32767).astype(np.int16)
    h = hashlib.sha256(q.tobytes()).hexdigest()[:ID_HASH_LEN]
    return 'kick-' + h


def _g(d, k):
    return d.get(k) if isinstance(d, dict) else None


# =====================================================================
# human-readable report
# =====================================================================
def print_report(r):
    bar = "=" * 66
    print(bar)
    print("  " + r['source'])
    print(bar)
    m = r['meta']
    sr_val = m.get('sr_nominal') or m.get('sr_effective', 0)
    print("  Format:      " + str(m['format']))
    print("  SR:          %.1f Hz" % sr_val)
    print("  Nyquist:     %.1f Hz" % m['nyquist_hz'])
    print("  Duration:    %.1f ms" % m['duration_ms'])
    print("  Peak:        %.4f" % m['peak'])
    print()
    print("  ID:          " + str(r.get('id')))
    print("  Onsets: %d   Classes: %d   Sizes: %s" %
          (r['loop']['n_onsets'], r['loop']['n_classes'],
           str(r['loop']['class_sizes'])))
    print()
    env_keys = ['attack_t_ms', 'attack_level', 'valley_t_ms',
                'valley_level_pct', 'reswell_t_ms', 'reswell_level_pct',
                'peak2_t_ms', 'peak2_level_pct', 'peak3_t_ms',
                'peak3_level_pct', 'body_100ms_pct', 'lvl_200ms_pct',
                'duration_ms', 'n_peaks']
    for k in r['kicks']:
        print("  -- class %d  (%d occurrences)  [%s] --" %
              (k['class_id'], k['n_instances'], k.get('class', '?')))
        print("    segment peak: %.4f   raw peak at: %.2f ms" %
              (k['seg_peak'], k.get('raw_peak_ms', 0)))
        det = k.get('detail', {})
        env = det.get('envelope', {})
        for key in env_keys:
            if key in env:
                v = env[key]
                fmt = "%-22s %10.3f" if isinstance(v, float) \
                    else "%-22s %10d"
                print("    " + fmt % (key, v))
        p = det.get('pitch', {})
        if p.get('f_settled_hz') is not None:
            print("    %-22s %10.2f" % ('f_settled_hz', p['f_settled_hz']))
        if p.get('f_settled_agreement_hz') is not None:
            print("    %-22s %10.2f" % ('f_settled_agreement_hz',
                                        p['f_settled_agreement_hz']))
        if p.get('f_settled_methods'):
            joined = ", ".join("%s=%.1f" % (mm, vv)
                               for mm, vv in p['f_settled_methods'].items())
            print("    f_settled_methods:    " + joined)
        c = det.get('content', {})
        print("    %-22s %10s" %
              ('click_present', str(c.get('click_present'))))
        for kk in ['click_ratio_db', 'harmonic_ratio_2f0_db']:
            if c.get(kk) is not None:
                print("    %-22s %10.2f" % (kk, c[kk]))
        print()


# =====================================================================
# JSON-safe export
# =====================================================================
def to_json(result):
    r = dict(result)
    r['kicks'] = []
    for k in result.get('kicks', []):
        kk = {kk: vv for kk, vv in k.items() if kk != '_arrays'}
        r['kicks'].append(kk)
    return ricks'].append(kk)
    return r


# =====================================================================
# human-readable report
# =====================================================================
def print_report(r):
    print("=" * 66)
    print("  " + r['source'])
    print("=" * 66)
    m = r['meta']
    sr_val = m.get('sr_nominal') or m.get('sr_effective', 0)
    print("  Format:      " + str(m['format']))
    print("  SR:          %.1f Hz" % sr_val)
    print("  Nyquist:     %.1f Hz" % m['nyquist_hz'])
    print("  Duration:    %.1f ms" % m['duration_ms'])
    print("  Peak:        %.4f" % m['peak'])
    print("")
    print("  ID:          " + str(r.get('id')))
    print("  Onsets: %d   Classes: %d   Sizes: %s" %
          (r['loop']['n_onsets'], r['loop']['n_classes'],
           str(r['loop']['class_sizes'])))
    print("")
    env_keys = ['attack_t_ms', 'attack_level', 'valley_t_ms',
                'valley_level_pct', 'reswell_t_ms', 'reswell_level_pct',
                'peak2_t_ms', 'peak2_level_pct', 'peak3_t_ms',
                'peak3_level_pct', 'body_100ms_pct', 'lvl_200ms_pct',
                'duration_ms', 'n_peaks']
    for k in r['kicks']:
        print("  -- class %d  (%d occurrences)  [%s] --" %
              (k['class_id'], k['n_instances'], k.get('class', '?')))
        print("    segment peak: %.4f   raw peak at: %.2f ms" %
              (k['seg_peak'], k.get('raw_peak_ms', 0)))
        det = k.get('detail', {})
        env = det.get('envelope', {})
        for key in env_keys:
            if key in env:
                v = env[key]
                fmt = "%-22s %10.3f" if isinstance(v, float) \
                    else "%-22s %10d"
                print("    " + fmt % (key, v))
        p = det.get('pitch', {})
        if p.get('f_settled_hz') is not None:
            print("    %-22s %10.2f" % ('f_settled_hz', p['f_settled_hz']))
        if p.get('f_settled_agreement_hz') is not None:
            print("    %-22s %10.2f" % ('f_settled_agreement_hz',
                                        p['f_settled_agreement_hz']))
        if p.get('f_settled_methods'):
            print("    f_settled_methods:    " +
                  ", ".join("%s=%.1f" % (mm, vv)
                            for mm, vv in p['f_settled_methods'].items()))
        c = det.get('content', {})
        print("    %-22s %10s" %
              ('click_present', str(c.get('click_present'))))
        for kk in ['click_ratio_db', 'harmonic_ratio_2f0_db']:
            if c.get(kk) is not None:
                print("    %-22s %10.2f" % (kk, c[kk]))
        print("")return r


# =====================================================================
# human-readable report
# =====================================================================
def print_report(r):
    print("=" * 66)
    print("  " + r['source'])
    print("=" * 66)
    m = r['meta']
    sr_val = m.get('sr_nominal') or m.get('sr_effective', 0)
    print("  Format:      " + str(m['format']))
    print("  SR:          %.1f Hz" % sr_val)
    print("  Nyquist:     %.1f Hz" % m['nyquist_hz'])
    print("  Duration:    %.1f ms" % m['duration_ms'])
    print("  Peak:        %.4f" % m['peak'])
    print("")
    print("  ID:          " + str(r.get('id')))
    print("  Onsets: %d   Classes: %d   Sizes: %s" %
          (r['loop']['n_onsets'], r['loop']['n_classes'],
           str(r['loop']['class_sizes'])))
    print("")
    env_keys = ['attack_t_ms', 'attack_level', 'valley_t_ms',
                'valley_level_pct', 'reswell_t_ms', 'reswell_level_pct',
                'peak2_t_ms', 'peak2_level_pct', 'peak3_t_ms',
                'peak3_level_pct', 'body_100ms_pct', 'lvl_200ms_pct',
                'duration_ms', 'n_peaks']
    for k in r['kicks']:
        print("  -- class %d  (%d occurrences)  [%s] --" %
              (k['class_id'], k['n_instances'], k.get('class', '?')))
        print("    segment peak: %.4f   raw peak at: %.2f ms" %
              (k['seg_peak'], k.get('raw_peak_ms', 0)))
        det = k.get('detail', {})
        env = det.get('envelope', {})
        for key in env_keys:
            if key in env:
                v = env[key]
                fmt = "%-22s %10.3f" if isinstance(v, float) \
                    else "%-22s %10d"
                print("    " + fmt % (key, v))
        p = det.get('pitch', {})
        if p.get('f_settled_hz') is not None:
            print("    %-22s %10.2f" % ('f_settled_hz', p['f_settled_hz']))
        if p.get('f_settled_agreement_hz') is not None:
            print("    %-22s %10.2f" % ('f_settled_agreement_hz',
                                        p['f_settled_agreement_hz']))
        if p.get('f_settled_methods'):
            print("    f_settled_methods:    " +
                  ", ".join("%s=%.1f" % (mm, vv)
                            for mm, vv in p['f_settled_methods'].items()))
        c = det.get('content', {})
        print("    %-22s %10s" %
              ('click_present', str(c.get('click_present'))))
        for kk in ['click_ratio_db', 'harmonic_ratio_2f0_db']:
            if c.get(kk) is not None:
                print("    %-22s %10.2f" % (kk, c[kk]))
        print("")
