#!/usr/bin/env python3
"""Concatenate analyzer/*.py into analyzer_bundle.py.

The package is the source of truth (for editing and for pytest).
The bundle is what index.html loads in Pyodide (one file, one fetch).

Relative imports (`from .X import Y`) are stripped — in the bundle
everything is at module scope. Absolute imports are hoisted to the top
and deduplicated. try/except import blocks are left untouched.

Run: python build.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
FILES = [
    'analyzer/config.py',
    'analyzer/io.py',
    'analyzer/onsets.py',
    'analyzer/envelope.py',
    'analyzer/pitch_methods.py',
    'analyzer/pitch.py',
    'analyzer/spectral.py',
    'analyzer/pipeline.py',
]
OUT = ROOT / 'analyzer_bundle.py'


def _strip_relative_imports_and_collect(text):
    """Return (absolute_imports, body_without_imports)."""
    imports, body = [], []
    for line in text.splitlines():
        s = line.strip()
        if s.startswith('from .') or s.startswith('from ..'):
            continue
        if s.startswith('import ') or s.startswith('from '):
            imports.append(s)
            continue
        body.append(line)
    return imports, '\n'.join(body)


def build(verbose=True):
    all_imports = set()
    chunks = []
    for rel in FILES:
        src = (ROOT / rel).read_text()
        imps, body = _strip_relative_imports_and_collect(src)
        all_imports.update(imps)
        chunks.append("# ============================================"
                      "=========================\n"
                      "# from %s\n"
                      "# ============================================"
                      "=========================\n%s" % (rel, body))

    head = '"""analyzer_bundle.py - GENERATED by build.py. Do not edit.\n\n'
    head += 'Edit files under analyzer/ and run `python build.py`.\n"""\n\n'
    head += '\n'.join(sorted(all_imports)) + '\n\n'
    output = head + '\n\n'.join(chunks) + '\n'

    if OUT.exists() and OUT.read_text() == output:
        if verbose:
            print("bundle up to date: %s" % OUT.name)
        return False
    OUT.write_text(output)
    if verbose:
        print("wrote %s (%d bytes)" % (OUT.name, len(output)))
    return True


if __name__ == '__main__':
    changed = build()
    if '--check' in sys.argv and changed:
        sys.exit(1)