#!/usr/bin/env python3
"""Concatenate analyzer/*.py into analyzer_bundle.py.

The package is the source of truth. The bundle is what index.html
loads in Pyodide (one file, one fetch).

Rules:
- Relative imports (`from .X import Y`) are stripped, including their
  multi-line continuation if any. Names resolve because in the bundle
  every module-level definition shares one namespace.
- Absolute imports at module scope are hoisted to the top and
  deduplicated. Multi-line absolute imports are preserved as a block.
- Imports inside try/except blocks or functions are preserved in place
  so `try: import librosa / except ImportError:` keeps working.

Run: python build.py
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
FILES = [
    'analyzer/config.py',
    'analyzer/io.py',
    'analyzer/onsets.py',
    'analyzer/envelope.py',
    'analyzer/pitch_methods.py',
    'analyzer/pitch.py',
    'analyzer/spectral.py',
    'analyzer/pipeline.py',
]
OUT = ROOT / 'analyzer_bundle.py'


def _is_top_level(line):
    """True if the line has no leading whitespace."""
    if line == '':
        return True
    return not line[:1].isspace()


def _strip_and_collect(text):
    imports, body = [], []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        s = line.strip()
        top = _is_top_level(line)
        if top and (s.startswith('from ') or s.startswith('import ')):
            # Multi-line? Count parens to find the end.
            depth = line.count('(') - line.count(')')
            block = [line]
            j = i + 1
            while depth > 0 and j < len(lines):
                block.append(lines[j])
                depth += lines[j].count('(') - lines[j].count(')')
                j += 1
            is_relative = (s.startswith('from .')
                           or s.startswith('from ..'))
            if not is_relative:
                imports.append('\n'.join(block))
            i = j
            continue
        body.append(line)
        i += 1
    return imports, '\n'.join(body)


def build(verbose=True):
    all_imports, seen = [], set()
    chunks = []
    for rel in FILES:
        src = (ROOT / rel).read_text()
        imps, body = _strip_and_collect(src)
        for imp in imps:
            key = imp.strip()
            if key not in seen:
                seen.add(key)
                all_imports.append(imp)
        bar = '#' * 60
        chunks.append('%s\n# from %s\n%s\n%s' % (bar, rel, bar, body))

    head = ('"""analyzer_bundle.py - GENERATED by build.py. Do not edit.\n\n'
            'Edit files under analyzer/ and run `python build.py`.\n"""\n\n')
    head += '\n'.join(all_imports) + '\n\n'
    output = head + '\n\n'.join(chunks) + '\n'

    if OUT.exists() and OUT.read_text() == output:
        if verbose:
            print("bundle up to date: %s" % OUT.name)
        return False
    OUT.write_text(output)
    if verbose:
        print("wrote %s (%d bytes)" % (OUT.name, len(output)))
    return True


if __name__ == '__main__':
    changed = build()
    if '--check' in sys.argv and changed:
        sys.exit(1)